#!/bin/sh

. /lib/functions.sh

OVERLAY="$( grep ' /overlay ' /proc/mounts )"

case "$ACTION" in
pressed)
	[ -z "$OVERLAY" ] && return 0
     ./../../dokme/shatel.sh &
  echo 1 > /../../noremove/checkmac.txt
  ./../../dokme/shootel.sh &


	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -lt 1 ]
	then
		 echo "nothing"
	elif [ "$SEEN" -ge 5 -a -n "$OVERLAY" ]
	then
		echo "FACTORY RESET" > /dev/console
		firstboot -y && reboot &

	fi
;;
esac

return 0
